version: '3'
services:
  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet
    tty: true
    network_mode: 'bridge'
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./pox:/pox
